USE [master]
GO
/****** Object:  Database [UcccPubMed]    Script Date: 05/12/2014 14:37:06 ******/
CREATE DATABASE [UcccPubMed] ON  PRIMARY 
( NAME = N'UcccPubMed', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\UcccPubMed.mdf' , SIZE = 199296KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'UcccPubMed_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\UcccPubMed_log.ldf' , SIZE = 265088KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [UcccPubMed] SET COMPATIBILITY_LEVEL = 100
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [UcccPubMed].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [UcccPubMed] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [UcccPubMed] SET ANSI_NULLS OFF
GO
ALTER DATABASE [UcccPubMed] SET ANSI_PADDING OFF
GO
ALTER DATABASE [UcccPubMed] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE [UcccPubMed] SET ARITHABORT OFF
GO
ALTER DATABASE [UcccPubMed] SET AUTO_CLOSE OFF
GO
ALTER DATABASE [UcccPubMed] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [UcccPubMed] SET AUTO_SHRINK OFF
GO
ALTER DATABASE [UcccPubMed] SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE [UcccPubMed] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [UcccPubMed] SET CURSOR_DEFAULT  GLOBAL
GO
ALTER DATABASE [UcccPubMed] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [UcccPubMed] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [UcccPubMed] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [UcccPubMed] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [UcccPubMed] SET  DISABLE_BROKER
GO
ALTER DATABASE [UcccPubMed] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE [UcccPubMed] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [UcccPubMed] SET TRUSTWORTHY OFF
GO
ALTER DATABASE [UcccPubMed] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO
ALTER DATABASE [UcccPubMed] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [UcccPubMed] SET READ_COMMITTED_SNAPSHOT OFF
GO
ALTER DATABASE [UcccPubMed] SET HONOR_BROKER_PRIORITY OFF
GO
ALTER DATABASE [UcccPubMed] SET  READ_WRITE
GO
ALTER DATABASE [UcccPubMed] SET RECOVERY FULL
GO
ALTER DATABASE [UcccPubMed] SET  MULTI_USER
GO
ALTER DATABASE [UcccPubMed] SET PAGE_VERIFY CHECKSUM
GO
ALTER DATABASE [UcccPubMed] SET DB_CHAINING OFF
GO
EXEC sys.sp_db_vardecimal_storage_format N'UcccPubMed', N'ON'
GO
USE [UcccPubMed]
GO
/****** Object:  Table [dbo].[REJECT_PUBLICATION]    Script Date: 05/12/2014 14:37:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[REJECT_PUBLICATION](
	[reject_publication_id] [int] IDENTITY(1,1) NOT NULL,
	[pmid] [int] NULL,
	[note] [varchar](1000) NULL,
 CONSTRAINT [PK_PUBLICATION_REJECT] PRIMARY KEY CLUSTERED 
(
	[reject_publication_id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[PUBTYPE]    Script Date: 05/12/2014 14:37:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PUBTYPE](
	[pubtype_id] [int] IDENTITY(1,1) NOT NULL,
	[description] [varchar](100) NULL,
 CONSTRAINT [PK_L_PUBLICATION_TYPE] PRIMARY KEY CLUSTERED 
(
	[pubtype_id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[PUBLOG]    Script Date: 05/12/2014 14:37:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PUBLOG](
	[publog_id] [int] IDENTITY(1,1) NOT NULL,
	[value] [varchar](1000) NOT NULL,
	[log_date] [date] NULL,
 CONSTRAINT [PK_LOG] PRIMARY KEY CLUSTERED 
(
	[publog_id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[L_YES_NO]    Script Date: 05/12/2014 14:37:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[L_YES_NO](
	[l_yes_no_id] [int] IDENTITY(1,1) NOT NULL,
	[description] [varchar](10) NULL,
 CONSTRAINT [PK_L_YES_NO] PRIMARY KEY CLUSTERED 
(
	[l_yes_no_id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[L_ROLE]    Script Date: 05/12/2014 14:37:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[L_ROLE](
	[l_role_id] [int] IDENTITY(1,1) NOT NULL,
	[description] [varchar](50) NOT NULL,
 CONSTRAINT [PK_L_ROLE] PRIMARY KEY CLUSTERED 
(
	[l_role_id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[L_RESOURCE]    Script Date: 05/12/2014 14:37:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[L_RESOURCE](
	[l_resource_id] [int] IDENTITY(1,1) NOT NULL,
	[description] [varchar](100) NOT NULL,
 CONSTRAINT [PK_L_SHARED_RESOURCE] PRIMARY KEY CLUSTERED 
(
	[l_resource_id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[L_PROGRAMMATIC]    Script Date: 05/12/2014 14:37:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[L_PROGRAMMATIC](
	[l_programmatic_id] [int] IDENTITY(1,1) NOT NULL,
	[description] [varchar](50) NOT NULL,
	[symbol] [varchar](5) NULL,
 CONSTRAINT [PK_L_PROGRAMMATIC] PRIMARY KEY CLUSTERED 
(
	[l_programmatic_id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[L_PROGRAM]    Script Date: 05/12/2014 14:37:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[L_PROGRAM](
	[L_PROGRAM_ID] [int] NOT NULL,
	[PROGRAM_NAME] [varchar](50) NOT NULL,
	[ABBREVIATION] [varchar](10) NULL,
	[ACTIVATED_DATE] [smalldatetime] NULL,
	[DEACTIVATED_DATE] [smalldatetime] NULL,
 CONSTRAINT [PK_L_PROGRAM] PRIMARY KEY CLUSTERED 
(
	[L_PROGRAM_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[L_INSTITUTION]    Script Date: 05/12/2014 14:37:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[L_INSTITUTION](
	[L_INSTITUTION_ID] [int] IDENTITY(1,1) NOT NULL,
	[DESCRIPTION] [varchar](1000) NOT NULL,
	[ABBREVIATION] [varchar](100) NULL,
 CONSTRAINT [PK_L_INSTITUTION] PRIMARY KEY CLUSTERED 
(
	[L_INSTITUTION_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[L_FOCUS_GROUP]    Script Date: 05/12/2014 14:37:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[L_FOCUS_GROUP](
	[l_focus_group_id] [int] IDENTITY(1,1) NOT NULL,
	[l_program_id] [int] NOT NULL,
	[description] [varchar](200) NULL,
	[group_number] [int] NULL,
 CONSTRAINT [PK_L_FOCUS_GROUP] PRIMARY KEY CLUSTERED 
(
	[l_focus_group_id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[L_COLLECTIVE_NAME]    Script Date: 05/12/2014 14:37:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[L_COLLECTIVE_NAME](
	[l_collective_name_id] [int] IDENTITY(1,1) NOT NULL,
	[collective_name] [varchar](100) NULL,
 CONSTRAINT [PK_COLLECTIVE_NAME] PRIMARY KEY CLUSTERED 
(
	[l_collective_name_id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[L_CLIENT_STATUS]    Script Date: 05/12/2014 14:37:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[L_CLIENT_STATUS](
	[L_CLIENT_STATUS_ID] int IDENTITY(1,1),
	[DESCRIPTION] [varchar](20) NOT NULL
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[GRANT]    Script Date: 05/12/2014 14:37:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[GRANT](
	[grant_id] [int] IDENTITY(1,1) NOT NULL,
	[description] [varchar](50) NOT NULL,
 CONSTRAINT [PK_GRANT] PRIMARY KEY CLUSTERED 
(
	[grant_id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[COLLECTIVE_NAME_CLIENT]    Script Date: 05/12/2014 14:37:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[COLLECTIVE_NAME_CLIENT](
	[collective_name_client_id] [int] IDENTITY(1,1) NOT NULL,
	[l_collective_name_id] [int] NULL,
	[client_id] [int] NULL,
 CONSTRAINT [PK_COLLECTIVE_NAME_AUTHOR] PRIMARY KEY CLUSTERED 
(
	[collective_name_client_id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CLIENT]    Script Date: 05/12/2014 14:37:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CLIENT](
	[CLIENT_ID] [int] NOT NULL,
	[LAST_NAME] [varchar](100) NOT NULL,
	[FIRST_NAME] [varchar](100) NOT NULL,
	[MI] [varchar](1) NULL,
 CONSTRAINT [PK_CLIENT] PRIMARY KEY CLUSTERED 
(
	[CLIENT_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[PUBLICATION]    Script Date: 05/12/2014 14:37:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PUBLICATION](
	[publication_id] [int] IDENTITY(1,1) NOT NULL,
	[journal_title] [varchar](500) NULL,
	[issn] [varchar](20) NULL,
	[issn_type] [varchar](20) NULL,
	[volume] [varchar](50) NULL,
	[issue] [varchar](50) NULL,
	[MedlinePgn] [varchar](50) NULL,
	[pub_year] [int] NULL,
	[pub_season] [varchar](10) NULL,
	[pub_month] [varchar](10) NULL,
	[pub_day] [int] NULL,
	[MedlineDate] [varchar](30) NULL,
	[entrez_year] [int] NULL,
	[entrez_month] [int] NULL,
	[entrez_day] [int] NULL,
	[pubmed_year] [int] NULL,
	[pubmed_month] [int] NULL,
	[pubmed_day] [int] NULL,
	[article_title] [nvarchar](max) NULL,
	[ISOAbbreviation] [varchar](max) NULL,
	[abstract_text] [nvarchar](max) NULL,
	[pmid] [int] NULL,
	[pmcid] [varchar](50) NULL,
	[CollectiveName] [nchar](100) NULL,
	[article_e_year] [varchar](50) NULL,
	[article_e_month] [varchar](50) NULL,
	[article_e_day] [varchar](50) NULL,
 CONSTRAINT [PK_PUBLICATION] PRIMARY KEY CLUSTERED 
(
	[publication_id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PUBLICATION] ON [dbo].[PUBLICATION] 
(
	[publication_id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_PUBLICATION_PMID] ON [dbo].[PUBLICATION] 
(
	[pmid] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PUB_USER]    Script Date: 05/12/2014 14:37:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PUB_USER](
	[pub_user_id] [int] IDENTITY(1,1) NOT NULL,
	[l_role_id] [int] NULL,
	[last_name] [varchar](20) NULL,
	[first_name] [varchar](20) NULL,
	[user_name] [varchar](20) NULL,
	[password] [varchar](20) NULL,
	[client_id] [int] NULL
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[PROGRAM_LEADER]    Script Date: 05/12/2014 14:37:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PROGRAM_LEADER](
	[program_leader_id] [int] IDENTITY(1,1) NOT NULL,
	[l_program_id] [int] NOT NULL,
	[client_id] [int] NOT NULL,
 CONSTRAINT [PK_PROGRAM_LEADER] PRIMARY KEY CLUSTERED 
(
	[program_leader_id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AUTHOR]    Script Date: 05/12/2014 14:37:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AUTHOR](
	[author_id] [int] IDENTITY(1,1) NOT NULL,
	[LastName] [nvarchar](100) NULL,
	[ForeName] [nvarchar](100) NULL,
	[Initials] [nvarchar](50) NULL,
	[Suffix] [nvarchar](50) NULL,
	[client_id] [int] NULL,
	[confirm_id] [int] NULL,
 CONSTRAINT [PK_AUTHOR] PRIMARY KEY CLUSTERED 
(
	[author_id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CLIENT_STATUS]    Script Date: 05/12/2014 14:37:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CLIENT_STATUS](
	[CLIENT_STATUS_ID] [int] NOT NULL,
	[CLIENT_ID] [int] NOT NULL,
	[L_CLIENT_STATUS_ID] [int] NOT NULL,
	[START_DATE] [smalldatetime] NULL,
	[END_DATE] [smalldatetime] NULL,
	[NOTE] [varchar](500) NULL
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[CLIENT_PROGRAM]    Script Date: 05/12/2014 14:37:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CLIENT_PROGRAM](
	[CLIENT_PROGRAM_ID] [int] NOT NULL,
	[CLIENT_ID] [int] NOT NULL,
	[L_PROGRAM_ID] [int] NOT NULL,
	[PRIMARY_PROGRAM] [int] NOT NULL,
	[START_DATE] [smalldatetime] NULL,
	[END_DATE] [smalldatetime] NULL,
	[NOTE] [varchar](1000) NULL,
 CONSTRAINT [PK_CLIENT_PROGRAM] PRIMARY KEY CLUSTERED 
(
	[CLIENT_PROGRAM_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[CLIENT_INSTITUTION]    Script Date: 05/12/2014 14:37:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CLIENT_INSTITUTION](
	[CLIENT_INSTITUTION_ID] [int] NOT NULL,
	[CLIENT_ID] [int] NOT NULL,
	[L_INSTITUTION_ID] [int] NOT NULL,
	[PRIMARY_INSTITUTION] [int] NOT NULL,
	[START_DATE] [smalldatetime] NULL,
	[END_DATE] [smalldatetime] NULL,
	[NOTE] [varchar](500) NULL,
 CONSTRAINT [PK_CLIENT_INSTITUTION] PRIMARY KEY CLUSTERED 
(
	[CLIENT_INSTITUTION_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[PUBLICATION_RESOURCE]    Script Date: 05/12/2014 14:37:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PUBLICATION_RESOURCE](
	[publication_resource_id] [int] IDENTITY(1,1) NOT NULL,
	[publication_id] [int] NULL,
	[l_resource_id] [int] NULL,
 CONSTRAINT [PK_PUBLICATION_RESOURCE] PRIMARY KEY CLUSTERED 
(
	[publication_resource_id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PUBLICATION_PUBTYPE]    Script Date: 05/12/2014 14:37:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PUBLICATION_PUBTYPE](
	[publication_pubtype_id] [int] IDENTITY(1,1) NOT NULL,
	[publication_id] [int] NOT NULL,
	[pubtype_id] [int] NOT NULL,
 CONSTRAINT [PK_PUBLICATION_PUBTYPE] PRIMARY KEY CLUSTERED 
(
	[publication_pubtype_id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PUBLICATION_PROGRAMMATIC]    Script Date: 05/12/2014 14:37:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PUBLICATION_PROGRAMMATIC](
	[publication_programmatic_id] [int] IDENTITY(1,1) NOT NULL,
	[publication_id] [int] NOT NULL,
	[l_program_id] [int] NOT NULL,
	[l_programmatic_id] [int] NULL,
 CONSTRAINT [PK_PUBLICATION_PROGRAMMATIC_1] PRIMARY KEY CLUSTERED 
(
	[publication_programmatic_id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PUBLICATION_PROGRAM]    Script Date: 05/12/2014 14:37:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PUBLICATION_PROGRAM](
	[publication_program_id] [int] IDENTITY(1,1) NOT NULL,
	[publication_id] [int] NOT NULL,
	[l_program_id] [int] NOT NULL,
	[l_focus_group_id] [int] NULL,
 CONSTRAINT [PK_PUBLICATION_PROGRAM_1] PRIMARY KEY CLUSTERED 
(
	[publication_program_id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PUBLICATION_PROCESSING]    Script Date: 05/12/2014 14:37:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PUBLICATION_PROCESSING](
	[publication_processing_id] [int] IDENTITY(1,1) NOT NULL,
	[publication_id] [int] NULL,
	[l_programmatic_id] [int] NULL,
	[authorlist] [nvarchar](max) NULL,
	[authorlist_no_inst] [nvarchar](max) NULL,
	[publication_date] [date] NULL,
	[citation] [int] NULL,
	[citation_date] [date] NULL,
	[final_confirm_id] [int] NULL,
	[address_confirm_id] [int] NULL,
	[name_confirm_id] [int] NULL,
	[full_text_url] [varchar](400) NULL,
	[formated_article_title] [nvarchar](max) NULL,
	[epub_date] [date] NULL,
	[review_editorial] [bit] NULL,
 CONSTRAINT [PK_PUBLICATION_PROCESSING] PRIMARY KEY CLUSTERED 
(
	[publication_processing_id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[PUBLICATION_GRANT]    Script Date: 05/12/2014 14:37:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PUBLICATION_GRANT](
	[publication_grant_id] [int] IDENTITY(1,1) NOT NULL,
	[publication_id] [int] NOT NULL,
	[grant_id] [int] NOT NULL,
 CONSTRAINT [PK_PUBLICATION_GRANT] PRIMARY KEY CLUSTERED 
(
	[publication_grant_id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PUBLICATION_AUTHOR]    Script Date: 05/12/2014 14:37:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PUBLICATION_AUTHOR](
	[publication_author_id] [int] IDENTITY(1,1) NOT NULL,
	[publication_id] [int] NOT NULL,
	[author_id] [int] NOT NULL,
 CONSTRAINT [PK_PUBLICATION_AUTHOR_1] PRIMARY KEY CLUSTERED 
(
	[publication_author_id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  ForeignKey [FK_PUB_USER_CLIENT]    Script Date: 05/12/2014 14:37:06 ******/
ALTER TABLE [dbo].[PUB_USER]  WITH CHECK ADD  CONSTRAINT [FK_PUB_USER_CLIENT] FOREIGN KEY([client_id])
REFERENCES [dbo].[CLIENT] ([CLIENT_ID])
GO
ALTER TABLE [dbo].[PUB_USER] CHECK CONSTRAINT [FK_PUB_USER_CLIENT]
GO
/****** Object:  ForeignKey [FK_PUB_USER_L_ROLE]    Script Date: 05/12/2014 14:37:06 ******/
ALTER TABLE [dbo].[PUB_USER]  WITH CHECK ADD  CONSTRAINT [FK_PUB_USER_L_ROLE] FOREIGN KEY([l_role_id])
REFERENCES [dbo].[L_ROLE] ([l_role_id])
GO
ALTER TABLE [dbo].[PUB_USER] CHECK CONSTRAINT [FK_PUB_USER_L_ROLE]
GO
/****** Object:  ForeignKey [FK_PROGRAM_LEADER_CLIENT]    Script Date: 05/12/2014 14:37:06 ******/
ALTER TABLE [dbo].[PROGRAM_LEADER]  WITH CHECK ADD  CONSTRAINT [FK_PROGRAM_LEADER_CLIENT] FOREIGN KEY([client_id])
REFERENCES [dbo].[CLIENT] ([CLIENT_ID])
GO
ALTER TABLE [dbo].[PROGRAM_LEADER] CHECK CONSTRAINT [FK_PROGRAM_LEADER_CLIENT]
GO
/****** Object:  ForeignKey [FK_PROGRAM_LEADER_L_PROGRAM]    Script Date: 05/12/2014 14:37:06 ******/
ALTER TABLE [dbo].[PROGRAM_LEADER]  WITH CHECK ADD  CONSTRAINT [FK_PROGRAM_LEADER_L_PROGRAM] FOREIGN KEY([l_program_id])
REFERENCES [dbo].[L_PROGRAM] ([L_PROGRAM_ID])
GO
ALTER TABLE [dbo].[PROGRAM_LEADER] CHECK CONSTRAINT [FK_PROGRAM_LEADER_L_PROGRAM]
GO
/****** Object:  ForeignKey [FK_AUTHOR_CLIENT]    Script Date: 05/12/2014 14:37:06 ******/
ALTER TABLE [dbo].[AUTHOR]  WITH CHECK ADD  CONSTRAINT [FK_AUTHOR_CLIENT] FOREIGN KEY([client_id])
REFERENCES [dbo].[CLIENT] ([CLIENT_ID])
GO
ALTER TABLE [dbo].[AUTHOR] CHECK CONSTRAINT [FK_AUTHOR_CLIENT]
GO
/****** Object:  ForeignKey [FK_AUTHOR_L_YES_NO]    Script Date: 05/12/2014 14:37:06 ******/
ALTER TABLE [dbo].[AUTHOR]  WITH CHECK ADD  CONSTRAINT [FK_AUTHOR_L_YES_NO] FOREIGN KEY([confirm_id])
REFERENCES [dbo].[L_YES_NO] ([l_yes_no_id])
GO
ALTER TABLE [dbo].[AUTHOR] CHECK CONSTRAINT [FK_AUTHOR_L_YES_NO]
GO
/****** Object:  ForeignKey [FK_CLIENT_STATUS_CLIENT]    Script Date: 05/12/2014 14:37:06 ******/
ALTER TABLE [dbo].[CLIENT_STATUS]  WITH CHECK ADD  CONSTRAINT [FK_CLIENT_STATUS_CLIENT] FOREIGN KEY([CLIENT_ID])
REFERENCES [dbo].[CLIENT] ([CLIENT_ID])
GO
ALTER TABLE [dbo].[CLIENT_STATUS] CHECK CONSTRAINT [FK_CLIENT_STATUS_CLIENT]
GO
/****** Object:  ForeignKey [FK_CLIENT_PROGRAM_CLIENT]    Script Date: 05/12/2014 14:37:06 ******/
ALTER TABLE [dbo].[CLIENT_PROGRAM]  WITH CHECK ADD  CONSTRAINT [FK_CLIENT_PROGRAM_CLIENT] FOREIGN KEY([CLIENT_ID])
REFERENCES [dbo].[CLIENT] ([CLIENT_ID])
GO
ALTER TABLE [dbo].[CLIENT_PROGRAM] CHECK CONSTRAINT [FK_CLIENT_PROGRAM_CLIENT]
GO
/****** Object:  ForeignKey [FK_CLIENT_PROGRAM_L_PROGRAM]    Script Date: 05/12/2014 14:37:06 ******/
ALTER TABLE [dbo].[CLIENT_PROGRAM]  WITH CHECK ADD  CONSTRAINT [FK_CLIENT_PROGRAM_L_PROGRAM] FOREIGN KEY([L_PROGRAM_ID])
REFERENCES [dbo].[L_PROGRAM] ([L_PROGRAM_ID])
GO
ALTER TABLE [dbo].[CLIENT_PROGRAM] CHECK CONSTRAINT [FK_CLIENT_PROGRAM_L_PROGRAM]
GO
/****** Object:  ForeignKey [FK_CLIENT_INSTITUTION_CLIENT]    Script Date: 05/12/2014 14:37:06 ******/
ALTER TABLE [dbo].[CLIENT_INSTITUTION]  WITH CHECK ADD  CONSTRAINT [FK_CLIENT_INSTITUTION_CLIENT] FOREIGN KEY([CLIENT_ID])
REFERENCES [dbo].[CLIENT] ([CLIENT_ID])
GO
ALTER TABLE [dbo].[CLIENT_INSTITUTION] CHECK CONSTRAINT [FK_CLIENT_INSTITUTION_CLIENT]
GO
/****** Object:  ForeignKey [FK_CLIENT_INSTITUTION_L_INSTITUTION]    Script Date: 05/12/2014 14:37:06 ******/
ALTER TABLE [dbo].[CLIENT_INSTITUTION]  WITH CHECK ADD  CONSTRAINT [FK_CLIENT_INSTITUTION_L_INSTITUTION] FOREIGN KEY([L_INSTITUTION_ID])
REFERENCES [dbo].[L_INSTITUTION] ([L_INSTITUTION_ID])
GO
ALTER TABLE [dbo].[CLIENT_INSTITUTION] CHECK CONSTRAINT [FK_CLIENT_INSTITUTION_L_INSTITUTION]
GO
/****** Object:  ForeignKey [FK_PUBLICATION_RESOURCE_L_RESOURCE]    Script Date: 05/12/2014 14:37:06 ******/
ALTER TABLE [dbo].[PUBLICATION_RESOURCE]  WITH CHECK ADD  CONSTRAINT [FK_PUBLICATION_RESOURCE_L_RESOURCE] FOREIGN KEY([l_resource_id])
REFERENCES [dbo].[L_RESOURCE] ([l_resource_id])
GO
ALTER TABLE [dbo].[PUBLICATION_RESOURCE] CHECK CONSTRAINT [FK_PUBLICATION_RESOURCE_L_RESOURCE]
GO
/****** Object:  ForeignKey [FK_PUBLICATION_RESOURCE_PUBLICATION]    Script Date: 05/12/2014 14:37:06 ******/
ALTER TABLE [dbo].[PUBLICATION_RESOURCE]  WITH CHECK ADD  CONSTRAINT [FK_PUBLICATION_RESOURCE_PUBLICATION] FOREIGN KEY([publication_id])
REFERENCES [dbo].[PUBLICATION] ([publication_id])
GO
ALTER TABLE [dbo].[PUBLICATION_RESOURCE] CHECK CONSTRAINT [FK_PUBLICATION_RESOURCE_PUBLICATION]
GO
/****** Object:  ForeignKey [FK_PUBLICATION_PUBTYPE_PUBTYPE]    Script Date: 05/12/2014 14:37:06 ******/
ALTER TABLE [dbo].[PUBLICATION_PUBTYPE]  WITH CHECK ADD  CONSTRAINT [FK_PUBLICATION_PUBTYPE_PUBTYPE] FOREIGN KEY([pubtype_id])
REFERENCES [dbo].[PUBTYPE] ([pubtype_id])
GO
ALTER TABLE [dbo].[PUBLICATION_PUBTYPE] CHECK CONSTRAINT [FK_PUBLICATION_PUBTYPE_PUBTYPE]
GO
/****** Object:  ForeignKey [FK_PUBLICATION_TYPE_PUBLICATION]    Script Date: 05/12/2014 14:37:06 ******/
ALTER TABLE [dbo].[PUBLICATION_PUBTYPE]  WITH CHECK ADD  CONSTRAINT [FK_PUBLICATION_TYPE_PUBLICATION] FOREIGN KEY([publication_id])
REFERENCES [dbo].[PUBLICATION] ([publication_id])
GO
ALTER TABLE [dbo].[PUBLICATION_PUBTYPE] CHECK CONSTRAINT [FK_PUBLICATION_TYPE_PUBLICATION]
GO
/****** Object:  ForeignKey [FK_PUBLICATION_PROGRAMMATIC_L_PROGRAM]    Script Date: 05/12/2014 14:37:06 ******/
ALTER TABLE [dbo].[PUBLICATION_PROGRAMMATIC]  WITH CHECK ADD  CONSTRAINT [FK_PUBLICATION_PROGRAMMATIC_L_PROGRAM] FOREIGN KEY([l_program_id])
REFERENCES [dbo].[L_PROGRAM] ([L_PROGRAM_ID])
GO
ALTER TABLE [dbo].[PUBLICATION_PROGRAMMATIC] CHECK CONSTRAINT [FK_PUBLICATION_PROGRAMMATIC_L_PROGRAM]
GO
/****** Object:  ForeignKey [FK_PUBLICATION_PROGRAMMATIC_L_PROGRAMMATIC]    Script Date: 05/12/2014 14:37:06 ******/
ALTER TABLE [dbo].[PUBLICATION_PROGRAMMATIC]  WITH CHECK ADD  CONSTRAINT [FK_PUBLICATION_PROGRAMMATIC_L_PROGRAMMATIC] FOREIGN KEY([l_programmatic_id])
REFERENCES [dbo].[L_PROGRAMMATIC] ([l_programmatic_id])
GO
ALTER TABLE [dbo].[PUBLICATION_PROGRAMMATIC] CHECK CONSTRAINT [FK_PUBLICATION_PROGRAMMATIC_L_PROGRAMMATIC]
GO
/****** Object:  ForeignKey [FK_PUBLICATION_PROGRAMMATIC_PUBLICATION]    Script Date: 05/12/2014 14:37:06 ******/
ALTER TABLE [dbo].[PUBLICATION_PROGRAMMATIC]  WITH CHECK ADD  CONSTRAINT [FK_PUBLICATION_PROGRAMMATIC_PUBLICATION] FOREIGN KEY([publication_id])
REFERENCES [dbo].[PUBLICATION] ([publication_id])
GO
ALTER TABLE [dbo].[PUBLICATION_PROGRAMMATIC] CHECK CONSTRAINT [FK_PUBLICATION_PROGRAMMATIC_PUBLICATION]
GO
/****** Object:  ForeignKey [FK_PUBLICATION_PROGRAM_L_FOCUS_GROUP]    Script Date: 05/12/2014 14:37:06 ******/
ALTER TABLE [dbo].[PUBLICATION_PROGRAM]  WITH CHECK ADD  CONSTRAINT [FK_PUBLICATION_PROGRAM_L_FOCUS_GROUP] FOREIGN KEY([l_focus_group_id])
REFERENCES [dbo].[L_FOCUS_GROUP] ([l_focus_group_id])
GO
ALTER TABLE [dbo].[PUBLICATION_PROGRAM] CHECK CONSTRAINT [FK_PUBLICATION_PROGRAM_L_FOCUS_GROUP]
GO
/****** Object:  ForeignKey [FK_PUBLICATION_PROGRAM_L_PROGRAM]    Script Date: 05/12/2014 14:37:06 ******/
ALTER TABLE [dbo].[PUBLICATION_PROGRAM]  WITH CHECK ADD  CONSTRAINT [FK_PUBLICATION_PROGRAM_L_PROGRAM] FOREIGN KEY([l_program_id])
REFERENCES [dbo].[L_PROGRAM] ([L_PROGRAM_ID])
GO
ALTER TABLE [dbo].[PUBLICATION_PROGRAM] CHECK CONSTRAINT [FK_PUBLICATION_PROGRAM_L_PROGRAM]
GO
/****** Object:  ForeignKey [FK_PUBLICATION_PROGRAM_PUBLICATION]    Script Date: 05/12/2014 14:37:06 ******/
ALTER TABLE [dbo].[PUBLICATION_PROGRAM]  WITH CHECK ADD  CONSTRAINT [FK_PUBLICATION_PROGRAM_PUBLICATION] FOREIGN KEY([publication_id])
REFERENCES [dbo].[PUBLICATION] ([publication_id])
GO
ALTER TABLE [dbo].[PUBLICATION_PROGRAM] CHECK CONSTRAINT [FK_PUBLICATION_PROGRAM_PUBLICATION]
GO
/****** Object:  ForeignKey [FK_PUBLICATION_DERIVED_L_PROGRAMMATIC]    Script Date: 05/12/2014 14:37:06 ******/
ALTER TABLE [dbo].[PUBLICATION_PROCESSING]  WITH CHECK ADD  CONSTRAINT [FK_PUBLICATION_DERIVED_L_PROGRAMMATIC] FOREIGN KEY([l_programmatic_id])
REFERENCES [dbo].[L_PROGRAMMATIC] ([l_programmatic_id])
GO
ALTER TABLE [dbo].[PUBLICATION_PROCESSING] CHECK CONSTRAINT [FK_PUBLICATION_DERIVED_L_PROGRAMMATIC]
GO
/****** Object:  ForeignKey [FK_PUBLICATION_PROCESSING_L_YES_NO]    Script Date: 05/12/2014 14:37:06 ******/
ALTER TABLE [dbo].[PUBLICATION_PROCESSING]  WITH CHECK ADD  CONSTRAINT [FK_PUBLICATION_PROCESSING_L_YES_NO] FOREIGN KEY([name_confirm_id])
REFERENCES [dbo].[L_YES_NO] ([l_yes_no_id])
GO
ALTER TABLE [dbo].[PUBLICATION_PROCESSING] CHECK CONSTRAINT [FK_PUBLICATION_PROCESSING_L_YES_NO]
GO
/****** Object:  ForeignKey [FK_PUBLICATION_PROCESSING_L_YES_NO1]    Script Date: 05/12/2014 14:37:06 ******/
ALTER TABLE [dbo].[PUBLICATION_PROCESSING]  WITH CHECK ADD  CONSTRAINT [FK_PUBLICATION_PROCESSING_L_YES_NO1] FOREIGN KEY([address_confirm_id])
REFERENCES [dbo].[L_YES_NO] ([l_yes_no_id])
GO
ALTER TABLE [dbo].[PUBLICATION_PROCESSING] CHECK CONSTRAINT [FK_PUBLICATION_PROCESSING_L_YES_NO1]
GO
/****** Object:  ForeignKey [FK_PUBLICATION_PROCESSING_L_YES_NO2]    Script Date: 05/12/2014 14:37:06 ******/
ALTER TABLE [dbo].[PUBLICATION_PROCESSING]  WITH CHECK ADD  CONSTRAINT [FK_PUBLICATION_PROCESSING_L_YES_NO2] FOREIGN KEY([final_confirm_id])
REFERENCES [dbo].[L_YES_NO] ([l_yes_no_id])
GO
ALTER TABLE [dbo].[PUBLICATION_PROCESSING] CHECK CONSTRAINT [FK_PUBLICATION_PROCESSING_L_YES_NO2]
GO
/****** Object:  ForeignKey [FK_PUBLICATION_PROCESSING_PUBLICATION]    Script Date: 05/12/2014 14:37:06 ******/
ALTER TABLE [dbo].[PUBLICATION_PROCESSING]  WITH CHECK ADD  CONSTRAINT [FK_PUBLICATION_PROCESSING_PUBLICATION] FOREIGN KEY([publication_id])
REFERENCES [dbo].[PUBLICATION] ([publication_id])
GO
ALTER TABLE [dbo].[PUBLICATION_PROCESSING] CHECK CONSTRAINT [FK_PUBLICATION_PROCESSING_PUBLICATION]
GO
/****** Object:  ForeignKey [FK_PUBLICATION_GRANT_GRANT]    Script Date: 05/12/2014 14:37:06 ******/
ALTER TABLE [dbo].[PUBLICATION_GRANT]  WITH CHECK ADD  CONSTRAINT [FK_PUBLICATION_GRANT_GRANT] FOREIGN KEY([grant_id])
REFERENCES [dbo].[GRANT] ([grant_id])
GO
ALTER TABLE [dbo].[PUBLICATION_GRANT] CHECK CONSTRAINT [FK_PUBLICATION_GRANT_GRANT]
GO
/****** Object:  ForeignKey [FK_PUBLICATION_GRANT_PUBLICATION]    Script Date: 05/12/2014 14:37:06 ******/
ALTER TABLE [dbo].[PUBLICATION_GRANT]  WITH CHECK ADD  CONSTRAINT [FK_PUBLICATION_GRANT_PUBLICATION] FOREIGN KEY([publication_id])
REFERENCES [dbo].[PUBLICATION] ([publication_id])
GO
ALTER TABLE [dbo].[PUBLICATION_GRANT] CHECK CONSTRAINT [FK_PUBLICATION_GRANT_PUBLICATION]
GO
/****** Object:  ForeignKey [FK_PUBLICATION_AUTHOR_AUTHOR]    Script Date: 05/12/2014 14:37:06 ******/
ALTER TABLE [dbo].[PUBLICATION_AUTHOR]  WITH CHECK ADD  CONSTRAINT [FK_PUBLICATION_AUTHOR_AUTHOR] FOREIGN KEY([author_id])
REFERENCES [dbo].[AUTHOR] ([author_id])
GO
ALTER TABLE [dbo].[PUBLICATION_AUTHOR] CHECK CONSTRAINT [FK_PUBLICATION_AUTHOR_AUTHOR]
GO
/****** Object:  ForeignKey [FK_PUBLICATION_AUTHOR_PUBLICATION]    Script Date: 05/12/2014 14:37:06 ******/
ALTER TABLE [dbo].[PUBLICATION_AUTHOR]  WITH CHECK ADD  CONSTRAINT [FK_PUBLICATION_AUTHOR_PUBLICATION] FOREIGN KEY([publication_id])
REFERENCES [dbo].[PUBLICATION] ([publication_id])
GO
ALTER TABLE [dbo].[PUBLICATION_AUTHOR] CHECK CONSTRAINT [FK_PUBLICATION_AUTHOR_PUBLICATION]
GO

insert into l_role (description) values ('Publication Specialist');
insert into l_role (description) values ('Program Leader');
insert into l_role (description) values ('Cancer Center Member');
insert into l_role (description) values ('Public');

insert into l_yes_no (description) values ('Yes');
insert into l_yes_no (description) values ('No');
insert into l_yes_no (description) values ('Unknown');
insert into l_yes_no (description) values ('Temp Yes');

insert into l_programmatic (description, symbol) values ('Inter-Programmatic', '*');
insert into l_programmatic (description, symbol) values ('Intra-Programmatic', '+');
insert into l_programmatic (description, symbol) values ('Inter-/Intra-Programmatic', '*+');
insert into l_programmatic (description, symbol) values ('n/a', '');

insert into l_client_status (description) values ('Pending');
insert into l_client_status (description) values ('Deferred');
insert into l_client_status (description) values ('Active');
insert into l_client_status (description) values ('Inactive');
insert into l_client_status (description) values ('Unknown');

insert into pub_user (l_role_id, last_name, first_name, user_name, password) values (1, 'admin', 'admin', 'admin', 'admin');

